Update README.md
Barre/privaxy pull request #25
Opened 2022-06-22 02:16 UTC by Darthagnon

Previous pull request didn't work?
https://github.com/Barre/privaxy/pull/22

2022-06-22 19:16 UTC, Barre requested changes
Thank you for this PR. I'd prefer to not endorse directly in the README any particular filter set. Otherwise, looks ok to me.

2022-06-26 20:32 UTC, Darthagnon commented
> particular filter set

Is that the reference to filterlists.com?

2022-06-26 20:49 UTC, Darthagnon commented
Hmmm... that's a point - are custom filterlists currently supported?

2022-12-03 05:20 UTC, ThinkChaos commented on README.md
> +Pre-built binaries for MacOS, Linux (x86_64) and Windows are provided on [Github releases](https://github.com/Barre/privaxy/releases).
The (not so) new spelling is "macOS":
```suggestion
Pre-built binaries for macOS, Linux (x86_64) and Windows are provided on [Github releases](https://github.com/Barre/privaxy/releases).
```

2022-12-03 05:20 UTC, ThinkChaos commented on README.md
> +   - MacOS: https://support.apple.com/guide/keychain-access/add-certificates-to-a-keychain-kyca2431/mac
```suggestion
   - macOS: https://support.apple.com/guide/keychain-access/add-certificates-to-a-keychain-kyca2431/mac
```

2022-12-03 05:20 UTC, ThinkChaos commented on README.md
> +   - MacOS: https://support.apple.com/guide/mac-help/change-proxy-settings-network-preferences-mac-mchlp2591/mac
```suggestion
   - macOS: https://support.apple.com/guide/mac-help/change-proxy-settings-network-preferences-mac-mchlp2591/mac
```

2023-08-14 10:21 UTC, closed without merging